version: '3'

services:

    nats-streaming:
        image: nats-streaming
        command: "-p 4223 -m 8223 -D -hbi 10s -hbt 5s -hbf 3"
        #        command: "--config '/opt/nats.yml' -D"
        working_dir: /app
        volumes:
        - .:/app
        networks:
        - local

networks:
    local:
        external: false
